$font = Space Mono

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = /home/lunaris/Pictures/bocchi_2.jpg
}

input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(0, 0, 0, 0.0)
    check_color = rgba(0, 0, 0, 0.0)
    fail_color = rgba(0, 0, 0, 0.0)

    font_color = rgba(c8c093aa)
    fade_on_empty = true
    rounding = 0

    font_family = $font
    placeholder_text = 
    fail_text = $PAMFAIL

    dots_size = 0.1
    dots_spacing = 0.5

    hide_input = false

    position = 0, 20
    halign = center
    valign = bottom
}

# TIME
label {
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgba(cfc9c2ff)
 
    position = 0, 40
    halign = center
    valign = center
}

# DATE
label {
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 20
    font_family = $font
    color = rgba(cfc9c2bb)

    position = 0, -55
    halign = center
    valign = center
}
