# variables
$mainMod=SUPER
$fileManager=nautilus
$terminal=kitty
$appLauncher=rofi -show drun
$browser=/home/lunaris/Downloads/zen/zen
# portable version of zen
$music=spotify
$screenshotRegion=grim -g "$(slurp)" - | wl-copy
$screenshotFull=grim - | wl-copy
$clipboard=cliphist list | rofi -dmenu | cliphist decode | wl-copy
$textEditor=code ## visual studio code

# monitor
monitor=,preferred,auto,1

# autostart
exec-once=waybar
exec-once=dunst ## notifications
exec-once=hyprctl setcursor ArcStarry 32
exec-once=hyprpaper
exec-once=wl-paste --watch cliphist store ## enable clipboard history
exec-once=fcitx5
exec-once=hyprpm reload ## plugins

# drawing tablet rotation
input {
  tablet {
    transform=1
  }
}

# general settings
general {
  gaps_in=10
  gaps_out=15
  border_size=2
  col.active_border=rgb(7aa2f7) rgb(7dcfff) 30deg
  col.inactive_border=rgb(414868)
  layout=dwindle
}

ecosystem {
  no_update_news=1
  no_donation_nag=1
}

misc {
  disable_hyprland_logo=1
  disable_splash_rendering=1
  animate_manual_resizes=1
}

binds {
  allow_workspace_cycles=1
}

# decorations
decoration {
  rounding=10

  blur {
    enabled=1
  }
}

# animations
animations {
  enabled=1
  bezier=bouncyZoom, 0.68, -0.55, 0.265, 1.55
  bezier=lessbouncyZoom, 0.68, -0.4, 0.265, 1.2
  bezier=standard, 0.2, 0, 0, 1
  animation=windows,1,4,bouncyZoom,popin 70%
  animation=windowsMove,1,3,lessbouncyZoom,popin 80%
  animation=fade,1,4,bouncyZoom
  animation=workspaces,1,4,standard,slide
}

# dwindle layout settings
dwindle {
  pseudotile=1
  preserve_split=1
}

# window rules
windowrulev2 = opacity 0.85 0.85,class:^(Code)$
windowrulev2 = opacity 0.85 0.85,class:^(org.gnome.Nautilus)$

# binds
bind=$mainMod, Q, killactive,
bind=$mainMod, M, exit,
bind=$mainMod, S, togglefloating,
bind=$mainMod, F, fullscreen, 0

bind=$mainMod, E, exec, $fileManager
bind=$mainMod, W, exec, wlogout --buttons-per-row 5
bind=$mainMod, SPACE, exec, $appLauncher
bind=$mainMod, RETURN, exec, $terminal
bind=, PRINT, exec, $screenshotFull
bind=ALT, PRINT, exec, $screenshotRegion
bind=$mainMod, B, exec, $browser
bind=$mainMod ALT, S, exec, $music
bind=$mainMod, V, exec, $clipboard
bind=$mainMod, C, exec, $textEditor
bind=$mainMod SHIFT, S, exec, fish -c lazyfav
bind=$mainMod, L, exec, hyprlock
bind=$mainMod, J, layoutmsg, togglesplit
bind=ALT, F10, pass, class:^(com\.obsproject\.Studio)$

# move focus
bind=$mainMod, left, movefocus,l
bind=$mainMod, right, movefocus,r
bind=$mainMod, up, movefocus,u
bind=$mainMod, down, movefocus,d

# move windows
bind=SHIFT $mainMod, left, movewindow, l
bind=SHIFT $mainMod, right, movewindow, r
bind=SHIFT $mainMod, up, movewindow, u
bind=SHIFT $mainMod, down, movewindow, d

bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow

# workspaces
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod, TAB, workspace, previous

bind=$mainMod, mouse_down, workspace, e+1
bind=$mainMod, mouse_up, workspace, e-1

# move to workspace
bind=$mainMod SHIFT, 1, movetoworkspace, 1
bind=$mainMod SHIFT, 2, movetoworkspace, 2
bind=$mainMod SHIFT, 3, movetoworkspace, 3
bind=$mainMod SHIFT, 4, movetoworkspace, 4
bind=$mainMod SHIFT, 5, movetoworkspace, 5
bind=$mainMod SHIFT, 6, movetoworkspace, 6
bind=$mainMod SHIFT, 7, movetoworkspace, 7
bind=$mainMod SHIFT, 8, movetoworkspace, 8
bind=$mainMod SHIFT, 9, movetoworkspace, 9
bind=$mainMod SHIFT, 0, movetoworkspace, 10
